### PR TITLE
fix Makefile.am in src dir

### PR DESCRIPTION
**Pull request by rtlanceroad**
1. I am not sure if this is a fix, I am on Crux Linux, this is a fix for me. (Thanks to @condy0919 )
2. Also you guys said installing **libffi-devel** can fix, I am curious about how that did the trick.
3. it's a great project, thanks,

@taviso Can you amswer my question and review this PR? Thanks for your time.

### CODE REVIEW

**Comment by rtlanceroad** [comment]
Also Crux Linux, no _devel_ pkg such thing. so i am really _curious_ :)

**Comment by cemeyer** [comment]
I would guess that on most Linux distributions, installing the devel package installs the headers directly in /usr/include, which is the global include path.  If the headers don't get installed in global /usr/include (e.g. Crux's libffi does this: https://crux.nu/ports/crux-3.2/opt/libffi/.footprint ), then we need $(FFI_CFLAGS) as the patch suggests.

(Fedora just drops them directly in /usr/include:)

```
$ rpm -ql libffi-devel
/usr/include/ffi-x86_64.h
/usr/include/ffi.h
/usr/include/ffitarget-x86_64.h
/usr/include/ffitarget.h
...
```

**Comment by taviso** [comment]
I thought the libstruct code didn't use any libffi stuff...but it seems like a harmless patch, so I think it's okay if this fixes it for you.

I can merge.

**Comment by taviso** [comment]
Done, thanks @rtlanceroad!

**Comment by cemeyer** [comment]
struct.c includes ffi.h. :-)

**Comment by rtlanceroad** [comment]
Thanks for the explaination for devel pkg @cemeyer  :)  And also merging this PR @taviso :)

**Comment by rtlanceroad** [comment]
I only see in struct.c, there are less than 10 lines related to ffi.h, maybe in the furture we want to drop libffi support?

**Comment by cemeyer** [comment]
Why bother?  We use ffi widely in the rest of ctypes.sh, so you would still need it installed to compile and use ctypes.sh.

**Comment by rtlanceroad** [comment]
ok ;)

**Pull request merged**
